INDIGO_WELCOME_MESSAGE: "Apprentissage à distance des mathématiques"
INDIGO_PRIMARY_COLOR: "##2c3e50" # secondary

# Footer links are dictionaries with a "title" and "url"
# To remove all links, write:
# INDIGO_FOOTER_NAV_LINKS: []
# INDIGO_FOOTER_LEGAL_LINKS: []
INDIGO_FOOTER_NAV_LINKS:
  - title: "À propos"
    url: "/about"
  - title: "Contact"
    url: "/contact"
INDIGO_FOOTER_LEGAL_LINKS:
    - title: "Mentions légales"
      url: "/tos"
